### PR TITLE
Bump version to 0.9.2

### PR DESCRIPTION
**Pull request by oronbz**
To include latest commit.

Please also push to `pod trunk` afterwards.

### CODE REVIEW

**Comment by sbarow** [comment]
Thanks @oronbz can you follow the steps in [RELEASING.md](https://github.com/uber/RIBs/blob/master/RELEASING.md) 1-4 and I'll do the rest.

**Comment by oronbz** [comment]
Thanks @sbarow, done for both iOS and Android.

**Comment by sbarow** [comment]
@artman does it make sense to bump the Android version inline with iOS?

**Comment by artman** [comment]
Yes, we need to come up with a strategy and helper script to bump versions on both Android and iOS at the same time. However, I don't see the need to bump the podspec version as #119 or #121 only changed template files.

**Comment by oronbz** [comment]
@artman you're definitely right, I've missed the fact that it's only template changes (one of them was actually mine). Would you like me to close this pull request or just rebase it when there's actual content that will affect gradle/pod?

**Comment by artman** [comment]
Yeah, let's close this out for now. Thanks!

**Pull request closed without merging**
