### PR TITLE
Bump RxSwift and deployment target

### PR DESCRIPTION
**Pull request by pavlodavydiuk**
**Description**:
- Added support for RxSwift 6.0.0
- Changed deployment target, because Xcode 12 raises the minimum known iOS deployment target from iOS 8.0 to iOS 9.0, otherwise Xcode will show a warning when using RIBs via SwiftPM.

### CODE REVIEW

**Review by maciejgurgul — APPROVED** [review]
great job!

**Review by piotrsmajek — APPROVED** [review]

**Review by ElonPark — APPROVED** [review]
LGTM 👍

**Review by kovpas — APPROVED** [review]

**Comment by kovpas** [comment]
Sorry for the delay folks. Approved 👍

**Comment by kielgillard** [comment]
@kovpas Any ETA on a merge and release?

**Comment by kovpas** [comment]
Merged!

**Pull request merged**
