### PR TITLE
Replace `SampleInteractable` with correct template on routers without…

### PR DESCRIPTION
**Pull request by oronbz**
… views

### CODE REVIEW

**Comment by sbarow** [comment]
Thanks @oronbz can you sign the CLA so we can merge this.

**Comment by oronbz** [comment]
Done @sbarow, thanks!

**Comment by oronbz** [comment]
@sbarow pusing to pod trunk? (:

**Comment by artman** [comment]
This didn't change files that are included by the podspec, so no need to push a new version. I wish we could still run custom installation scripts when a pod is installed to make sure that users have the correct templates, but I think that got deprecated, right?

**Comment by sbarow** [comment]
@artman we could use [prepare_command](https://guides.cocoapods.org/syntax/podspec.html#prepare_command) for this right?

**Pull request merged**
