### PR TITLE
Fix typo in 'Documentation' section of README

### PR DESCRIPTION
**Pull request by alexDtorres**
**Description**: This pull request contains a change to the README correcting a minor typo I noticed earlier. Creating pull request in case no one else has noticed this yet.

**Related issue(s)**: Documentation

### CODE REVIEW

**Comment by alexDtorres** [comment]
Did I submit this wrong? Forgot about it, and now realizing it was never reviewed. I'm not sure how to request a reviewer. 

Please help me out @artman 

Thank you!

**Review by alexDtorres — COMMENTED** [review]
Please review.

**Comment by alexDtorres** [comment]
This is a mess lol. Apologies in advance..

**Review by artman — APPROVED** [review]

**Comment by artman** [comment]
> Please help me out @artman

Can't really help you here. I no longer have review/merge privileges on this repo.

**Comment by alexDtorres** [comment]
@artman excuse my ignance. And thanks for the reply.

**Review by alexDtorres — COMMENTED** [review]
Can you please review?

**Comment by alexDtorres** [comment]
> Can you please review?

**Review by kovpas — APPROVED** [review]

**Comment by kovpas** [comment]
Thanks @alexDtorres!

**Pull request merged**
