### PR TITLE
Migrate from deprecated `@JvmDefault` to compiler option `-Xjvm-default=all`

### LINKED ISSUE #571: Migrate from deprecated `@JvmDefault` and `-Xjvm-default=enabled` to `-Xjvm-default=all`
We should move to `-Xjvm-default=all`. Per [docs](https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/):

> If you used the @JvmDefault annotation before, you can safely remove it and use one of the new modes. If you already used -Xjvm-default=enable, which generated only the default method implementations, you can now replace it with -Xjvm-default=all.

### PR DESCRIPTION
**Pull request by psteiger**
[Docs](https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/) state that:

> If you used the @JvmDefault annotation before, you can safely remove it and use one of the new modes. If you already used -Xjvm-default=enable, which generated only the default method implementations, you can now replace it with -Xjvm-default=all.

Fixes #571

### CODE REVIEW

**Comment by tyvsmith** [comment]
I believe there was an issue with regards to Bazel and this setting before. @jbarr21 @oliviernotteghem do you recall?

**Comment by psteiger** [comment]
> I believe there was an issue with regards to Bazel and this setting before. @jbarr21 @oliviernotteghem do you recall?

Probably [this issue](https://github.com/bazelbuild/rules_kotlin/issues/714) opened by @oliviernottenghem himself?

Should it matter for this project though? I understand Bazel will consume this library as an already-compiled binary, as opposed to building it. Bytecode will already be generated. Unless I'm missing something, so I'll wait for their input.

**Comment by oliviernotteghem** [comment]
@psteiger : please refer to [this PR](https://github.com/uber/RIBs/pull/495) for context on the issue @tyvsmith is referring to. I can help you verify changes you may make are compatible with Bazel (or you can simply build with Bazel a simple Android binary target having a dependencies on RIBs libraries)

**Comment by jbarr21** [comment]
This will be needed in order to compile against Kotlin 1.9

**Review by jbarr21 — APPROVED** [review]

**Pull request merged**
