### PR TITLE
Change Allowing Build with Xcode 10.2 & Swift 5 closes #317 & #316 

### LINKED ISSUE #317: [Bug] [iOS] Swift 5
Error when compiling under Swift 5, Xcode 10.2. Fixed by changing `open let dependency: DependencyType` to `public let dependency: DependencyType` in file `Component.swift`

### PR DESCRIPTION
**Pull request by WikipediaBrown**
I am contributing because I want to not have to edit the cocoapod when I use RIBs. I very much like this design pattern so I thought I'd contribute an easy layup. 

**Related issue(s)**: This PR closes #317 & #316

### CODE REVIEW

**Comment by ermik** [comment]
I think you should point this PR to `master`; you can see that your changes are obscured because the `contribute` branch is behind.

**Comment by ermik** [comment]
There are also #311 and #316 PRs which you have to review to see if it's better to do this as a collaboration on existing PRs

**Comment by ermik** [comment]
This can be closed following #321 & due to author's inactivity.

**Comment by kovpas** [comment]
Closing for now. I believe the project is working with Xcode 11.2 and swift 5 now.

**Pull request closed without merging**
