### PR TITLE
Added RIB's template option to create a corresponding Storyboard file

### PR DESCRIPTION
**Pull request by jarinosuke**
inspired by this idea: https://github.com/uber/RIBs/pull/171

### Changes

- 1. Added another checkbox to add storyboard
- 2. This checkbox is active only in case when "owns the corresponding view" is checked, and "with XIB' checkbox is inactive
- 3. Installation script copies "default" RIB files into template with Storyboard folder

### CODE REVIEW

**Comment by neakor** [comment]
I thought someone else had already merged this.

**Comment by sbarow** [comment]
Thanks @jarinosuke tried to use the web editor to fix merge conflicts, this should fix the issue. https://github.com/uber/RIBs/pull/175/commits/78200d55473a2606220ed4ef0bbae116ca8633b6

**Comment by jarinosuke** [comment]
@sbarow Thanks for your review! I've resolved conflicts, could you check this? 
https://github.com/uber/RIBs/pull/175/commits/ba560a5409881b8acfd87cb16c31dc2d924cb774

**Comment by ermik** [comment]
How does @uber engineering team work with regards to UI? I've heard storyboards are a pain in merge conflicts and code reviews. What are some of the recommendations you guys have on how to build UI elements that would be as wonderfully developer-friendly as RIBs themselves?

**Comment by rudro** [comment]
> How does @uber engineering team work with regards to UI? I've heard storyboards are a pain in merge conflicts and code reviews. What are some of the recommendations you guys have on how to build UI elements that would be as wonderfully developer-friendly as RIBs themselves?

@ermik Like a lot of large companies we build out UI purely in code. There are not a ton of wrappers/libraries/tools in use, but there are 2 things. 1) We use SnapKit (https://github.com/SnapKit/SnapKit) when doing auto layout and 2) The mobile platform team maintains a library that contains UI elements themed in the Uber style (most don't add much functionality, just styling, but there are a few complex widgets like a country picker and phone number entry and such)

**Pull request merged**
